services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: thesis
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  db:
    driver:
      local